#!/usr/bin/env node
/**
 * pnpm bootstrap <slug> [--name "<App Name>"]
 *
 * Local-only bootstrap for a freshly-cloned starter-kit instance. Renames the
 * Postgres schema, generates a SESSION_SECRET, writes .env.local pointing at
 * shared resources (Neon, Redis), and updates the root package.json. After
 * this, run `pnpm bootstrap:vercel <slug>` to provision the deploy.
 *
 * Idempotent — safe to re-run.
 */
import { execFileSync, execSync } from 'node:child_process'
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { glob } from 'node:fs/promises'
import path from 'node:path'

const ROOT = path.resolve(import.meta.dirname, '..')

// ── argv parsing ────────────────────────────────────────────────────────
const args = process.argv.slice(2)
const slug = args.find((a) => !a.startsWith('--'))
const nameFlagIdx = args.indexOf('--name')
const appName =
  nameFlagIdx >= 0 ? args[nameFlagIdx + 1] : slug ? toTitle(slug) : null

if (!slug) {
  console.error('usage: pnpm bootstrap <slug> [--name "<App Name>"]')
  process.exit(1)
}
if (!/^[a-z][a-z0-9-]{2,31}$/.test(slug)) {
  console.error(
    `× invalid slug "${slug}" — must be 3-32 chars, kebab-case, start with a letter`,
  )
  process.exit(1)
}
const TAKEN_PROJECT_SLUGS = new Set([
  'vibe-stack',
  'float',
  'ogp-watchdog',
  'pkm-v6',
  'tit-for-tat',
])
if (TAKEN_PROJECT_SLUGS.has(slug)) {
  console.error(
    `× slug "${slug}" matches an existing personal project; pick a fresh one`,
  )
  process.exit(1)
}

// Schema names use underscores (Postgres identifier rules) — no quoting needed.
const schemaName = slug.replaceAll('-', '_')

console.log(`◇ slug         : ${slug}`)
console.log(`◇ schema       : ${schemaName}`)
console.log(`◇ display name : ${appName}`)
console.log()

// ── 1. sed-rewrite hardcoded `vibe_stack` references ───────────────────
console.log('→ rewriting vibe_stack → ' + schemaName + ' across the tree')
const TARGET_GLOBS = [
  'packages/db/prisma/schema.prisma',
  'packages/db/prisma/migrations/**/*.sql',
  'apps/web/tests/db/utils.ts',
  'apps/web/tests/e2e/api-tokens.spec.ts',
  'apps/web/tests/e2e/setup/db-setup.ts',
  'apps/web/src/server/modules/file/file.service.ts',
]
let rewroteFiles = 0
for (const pattern of TARGET_GLOBS) {
  for await (const file of glob(pattern, { cwd: ROOT })) {
    const abs = path.join(ROOT, file)
    if (!existsSync(abs)) continue
    const before = readFileSync(abs, 'utf8')
    const after = before.replaceAll('vibe_stack', schemaName)
    if (before !== after) {
      writeFileSync(abs, after)
      rewroteFiles++
    }
  }
}
console.log(`  ${rewroteFiles} files rewritten`)

// ── 2. update root package.json name ───────────────────────────────────
const pkgPath = path.join(ROOT, 'package.json')
const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'))
const oldName = pkg.name
pkg.name = `@${slug}/monorepo`
if (oldName !== pkg.name) {
  writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + '\n')
  console.log(`→ root package.json name : ${oldName} → ${pkg.name}`)
}

// ── 3. SESSION_SECRET — reuse from keychain if it exists (idempotent) ──
let sessionSecret = keychainOpt(`claude-code:${slug}`, 'SESSION_SECRET')
if (sessionSecret) {
  console.log(`→ reusing SESSION_SECRET from claude-code:${slug}`)
} else {
  console.log(`→ generating SESSION_SECRET, storing in claude-code:${slug}`)
  sessionSecret = execSync('openssl rand -base64 32').toString().trim()
  execFileSync('security', [
    'add-generic-password',
    '-s', `claude-code:${slug}`,
    '-a', 'SESSION_SECRET',
    '-w', sessionSecret,
    '-U',
  ])
}

// ── 4. assemble .env.local ─────────────────────────────────────────────
console.log('→ writing .env.local from shared keychain entries')
const dbUrl = keychain('claude-code:shared-neon', 'DATABASE_URL')
const dbDirect = keychain('claude-code:shared-neon', 'DATABASE_URL_UNPOOLED')
const redisUrl = keychain('claude-code:shared-redis', 'REDIS_URL')
const redis = new URL(redisUrl)

const dbWithSchema = (url) =>
  url + (url.includes('?') ? '&' : '?') + 'schema=' + schemaName

const envLocal = `# Generated by scripts/bootstrap-app.mjs — re-run \`pnpm bootstrap ${slug}\` to refresh
# Shared Neon (per-app schema isolation via ?schema=)
DATABASE_URL=${dbWithSchema(dbUrl)}
DATABASE_URL_UNPOOLED=${dbWithSchema(dbDirect)}
DIRECT_URL=${dbWithSchema(dbDirect)}

# Shared Redis Cloud (per-app keyspace isolation via CACHE_KEY_PREFIX)
CACHE_HOSTNAME=${redis.hostname}
CACHE_PORT=${redis.port}
CACHE_USERNAME=${redis.username}
CACHE_PASSWORD=${decodeURIComponent(redis.password)}
CACHE_KEY_PREFIX=${slug}

# Iron-session secret (per-app)
SESSION_SECRET=${sessionSecret}

# App identity
NEXT_PUBLIC_APP_NAME=${appName}
NEXT_PUBLIC_APP_VERSION=0.0.1
LOG_LEVEL=info
`
writeFileSync(path.join(ROOT, '.env.local'), envLocal)
console.log(`  wrote .env.local (${envLocal.split('\n').length} lines)`)

// ── 5. summary ─────────────────────────────────────────────────────────
console.log()
console.log('✓ bootstrap-app done')
console.log()
console.log('Next:')
console.log(`  pnpm bootstrap:vercel ${slug}    # create Vercel project + deploy`)
console.log(`  pnpm bootstrap:sentry ${slug}    # create Sentry project + push DSN`)
console.log(`  pnpm bootstrap:blob ${slug}      # create Vercel Blob store + push token`)

// ── helpers ────────────────────────────────────────────────────────────
function keychain(service, account) {
  return execFileSync('security', [
    'find-generic-password',
    '-s', service,
    '-a', account,
    '-w',
  ])
    .toString()
    .trim()
}

function keychainOpt(service, account) {
  try {
    return keychain(service, account)
  } catch {
    return null
  }
}

function toTitle(s) {
  return s
    .split('-')
    .map((w) => w[0].toUpperCase() + w.slice(1))
    .join(' ')
}
